version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vestGO
      POSTGRES_PASSWORD: senhaVestGo2024